import React, { useState, useEffect, useContext } from 'react'
import { useRouter } from "next/router";
import { Background } from '../components/shows/Background';
import Head from 'next/head';
import Popular from '../utils/popular';
import Contents from '../components/shows/Contents';
import Router, { withRouter } from 'next/router';
import PageContext from '../context/PageContext';



const TvShows = () => {
  //const resultStorage = JSON.parse(localStorage.getItem('content')) || "[]"
  
  const [result, setResult] = useState([]);
  const [index, setIndex] = useState("");
  const [image, setImage] = useState("");

  useEffect(()=>{
    const res = JSON.parse(localStorage.getItem("result"))
    const idx = localStorage.getItem("index")
    const img = localStorage.getItem("img")
    //console.log("first")
   // console.log(res);
    if (res && idx && img){
        setResult(res);
        setIndex(idx);
        setImage(img);
    }  
}, [])
 
    console.log(result);
    console.log(index);
    console.log(image);


  return (
    <div className=''>
      <Head>
        <title>{Popular[Number(index)].title} |  </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background result={result} image={image} index={index} />
      {/* <Background image={image} index={index} /> */}
      <div className='cursor-default px-10'>
        <div className=' text-xl pt-5 pb-5'>vcgdks</div>
        {/* <Contents result={result} index={index}/> */}
      </div>
      
    </div>
  )
}

export default TvShows

// export async function getServerSresulteProps (context) {
//   console.log(context.query) 
//   // returns { result: episode.itunes.episode, title: episode.title}
  

//   //you can make DB queries using the data in context.query
//   return {
//       props: { 
//          result: context.query.result //pass it to the page props
//       }
//   }
// }
